### ISSUE TITLE
2nd story

### ISSUE THREAD

**Issue by volodymyr-kushnir** [KukuruzaAndrey/BSA-17-JS.-L1-Git-HW#3]
Hi, so far so good.
Let's see if you could please create a separate branch for 2nd story, add that story, push that branch to GitHub and merge it into your primary branch using GitHub's **New pull request** feature (you would need to select your source branch first, master would be your base).

**Comment by KukuruzaAndrey** [comment]
Fixed #4

**Comment by KukuruzaAndrey** [comment]
fix #4

**Comment by KukuruzaAndrey** [comment]
And Y No Auto Close?

**Comment by KukuruzaAndrey** [comment]
closes #3

**Comment by KukuruzaAndrey** [comment]
![](http://static1.fjcdn.com/thumbnails/comments/Hfw+he+finds+out+it+only+had+to+be+charged+_f92c25c26385fbd2ac58bf41aee83675.png)

**Comment by volodymyr-kushnir** [comment]
"Fixes #3" should go into **commit message** and not issue comments

**Comment by KukuruzaAndrey** [comment]
@volodymyr-kushnir

**Comment by volodymyr-kushnir** [comment]
@KukuruzaAndrey exactly, you got it. Now it says which commit closed this issue so it's easier to surfthe repository. Nice!

**Comment by KukuruzaAndrey** [comment]
Thanks for the hint) But i made mistake with "revert". Well, at least now I understand how it works
